### ISSUE TITLE
improve configuration section merging of vectors 

### ISSUE THREAD

**Issue by vbargsten** [rock-core/tools-orocosrb#134]
Currently, merging configuration sections with vectors results in an element-wise, recursive overwriting (or failure if overwrite=false). As a user, I would expect appending vector-like structures or a setting to select/define the behavior.
The recursive processing will also result in partial overwrites of elements of vectors within nested structures/maps, if the size differs.
I think it could be a useful feature for structuring more complex system configurations but needs improvement to be actually usable.

Example:
Consider applying the following configuration sections. If overwrite is enabled, you will end up with `joint_names: ["finger_1", "finger_2"]`, or a failure otherwise. Instead, I would expect `joint_names: ["joint_1", "joint_2", "finger_1", "finger_2"]`. In addition, you get a filter "f2", with coeffs `5, 6, 3, 4`.

```yaml
--- name:manipulator merge:true
joint_names: ["joint_1", "joint_2"]
filters:
    - name: "f1"
      coeffs: [1, 2, 3, 4]

--- name:gripper merge:true
joint_names: ["finger_1", "finger_2"]

filters:
    - name: "f2"
      coeffs: [5, 6]

```
